FROM node:14 as build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY . ./

RUN yarn install
RUN yarn build


FROM ubuntu:18.04

RUN apt update
RUN apt install nginx -y

COPY --from=build /app/build /var/www/html
COPY nginx.conf /etc/nginx/conf.d

RUN rm /etc/nginx/sites-available/default
RUN rm /etc/nginx/sites-enabled/default

CMD ["nginx", "-g", "daemon off;"]

