FROM node:16.15.1-buster-slim AS build

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY . ./

RUN yarn install
RUN yarn build


FROM nginx

COPY --from=build /app/build /usr/share/nginx/html


