server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    gzip on;
    gzip_min_length 1024;
    gzip_types application/javascript application/json image/svg+xml text/css text/plain;

    location /_nuxt/ {
        try_files $uri =404;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location ~ ^/(data|translations)/ {
        try_files $uri =404;
        add_header Cache-Control "no-cache";
    }

    location = /licenses.json {
        try_files $uri =404;
        add_header Cache-Control "no-cache";
    }

    location = /index.html {
        add_header Cache-Control "no-cache";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
